#include <iostream>
#include <string>
#include <unordered_map>
#include <vector>

using namespace std;

bool isAnagram(string s, string t)
{
    if(s.size() != t.size())
        return false;

    int i = 0;
    unordered_map<char, int> countS;
    unordered_map<char, int> countT;

    for (i = 0; i < s.size(); i++)
    {
        countS[s[i]]++;
        countT[t[i]]++;
    }

    for (i = 0; i < countS.size(); i++)
    {
        if (countS[i] != countT[i])
            return false;
    }

    return true;
}

// Test code generated by ChatGPT
int main()
{
    vector<pair<string, string>> tests = {
        {"anagram", "nagaram"}, // true
        {"rat", "car"},         // false
        {"", ""},               // true (both empty)
        {"a", "a"},             // true
        {"a", "b"},             // false
        {"listen", "silent"},   // true
        {"hello", "helo"},      // false
        {"abcd", "dcba"},       // true
        {"abcd", "abcde"}       // false (different lengths)
    };

    for (int i = 0; i < tests.size(); i++)
    {
        const string &s = tests[i].first;
        const string &t = tests[i].second;

        bool result = isAnagram(s, t);

        cout << "Test " << i + 1 << ": "
             << "\"" << s << "\" vs \"" << t << "\" -> "
             << (result ? "true" : "false") << endl << endl;
    }

    vector<bool> expected = {
        true, false, true, true, false, true, false, true, false};

    for (int i = 0; i < tests.size(); i++)
    {
        bool result = isAnagram(tests[i].first, tests[i].second);
        cout << "Test " << i + 1
             << (result == expected[i] ? " PASS" : " FAIL")
             << endl;
    }

    return 0;
}
